### ISSUE TITLE
MQTT queuing

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#155]
Hi, @DIOHz0r 

Please, remove in the back-end the queuing of MQTT messages that @btry implemented, and simplify the Android Agent in the same way. /cc @rafaelje 

Reference: https://github.com/flyve-mdm/flyve-mdm-glpi-plugin/issues/75

**Comment by btry** [comment]
more details:
 he idea is to remove several things 
- the retention of mqtt messages in the itemtype PluginFlyvemdmMqttUpdatequeue (the itemtype should disappear)
- the grouping of policies per purpose, designed for password policies
  - whan a password related policy changes, the mqtt message generated contains all 11 password related policies, because Android needs all these settings in its API to apply a change. I think the agent may retain settings in shared preferences to apply a setting without receiving all others. This is design may be a pain to handle other designs with other MDM platforms.

**Comment by btry** [comment]
Hi I began this task, and I have apparently good results for now. 

Unit tests will certainly break as they are not updated yet. Pushing a branch with the current work.
