### ISSUE TITLE
Enroll device once delete it from website

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/glpi-plugin#32]
### Expected behaviour
Enroll my device once delete it from website

### Actual behaviour
When I delete some device connected from website is impossible to reconnect this device again because I can't read the QR or logout

### Environment Details

- Flyve MDM version: 0.99.46

### Steps to reproduce the behaviour

1. Enroll a device
2. Create a fleet
3. Send fleet
4. Delete the device on website
5. Check the device
6. Try to Enroll again

**Comment by btry** [comment]
A QR code can ne used only once (except if a debug setting is enabled).

We still need to choose if we must try to unenroll a device if the admin deletes it. Currently, you need to stop the agent, reset its data and restart it to be able to enroll again. 

To properly reset an agent, unenroll it instead of deleting it. The agent will receive an unenrollment message and reset itself.
