### ISSUE TITLE
Error message format is wrong

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/glpi-plugin#425]
#### Observed Results:

When some error occur on the API the error now is not well format 

```
Value ["ERROR_RIGHT_MISSING","You don't have permission to perform this action."] of type org.json.JSONArray cannot be converted to JSONObject
 ```
#### Expected behavior:

Remove the text that is not required will be like:

```
["ERROR_RIGHT_MISSING","You don't have permission to perform this action."]
```

**Comment by btry** [comment]
Hi 

Can you show how to reproduce ?

Moreover the wrong message is strange. ```org.json.JSONArray``` makes me think about Java.

**Comment by btry** [comment]
If I read the following, I think the error is generated by the MDM agent, not the backend.

https://stackoverflow.com/questions/32715153/org-json-jsonarray-cannot-be-converted-to-jsonobject

Maybe you're expecting an JSON Object, but the backend sends a JSON array. I guess the MDM agent expects a JSON Object because it assumes the HTTP request will succeed. In this case, the backend sends a JSON object. 

If the HTTP request fails, the response is a JSON array, but the MDM agent does not handles this failure properly (still guessing).

**Comment by rafaelje** [comment]
I cannot reproduce the error again
