### ISSUE TITLE
Problem with automatic policy delete file

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/glpi-plugin#484]
When you delete an Add File policy from a fleet this create automatically a new policy to erase the file, but this last policy to erase the file is not sent to the agent

**To Reproduce**

1. Add any fleet to the device
1. Go to fleet
2. Add File policy with automatic delete checked
3. Delete this policy
4. The delete policy is on the list but is not sent to the agent

**Comment by rafaelje** [comment]
This issue happens with remove applications too

**Comment by DIOHz0r** [comment]
This issue is still present 'cause the problem is why the mqtt messages. The policy sends one empty message to let the agent know that the "deploy app/file" policy has been removed but it must also sends another publish message with the new task with the "remove app/file" body.

As you can see the top message was send by hand but it's missing on the mass action of "delete permanently" 
![imagen](https://user-images.githubusercontent.com/1426313/39895554-b9919676-5478-11e8-9666-4c1581ea9017.png)

**Comment by btry** [comment]
Here is my test result with the current develop branch:
- I deploy a file on a fleet with the remove_on_delete flag set
-  I remove the file deployment

![image](https://user-images.githubusercontent.com/14139801/39910858-6e06aeea-54f9-11e8-9229-2d3e0826b542.png)

**Comment by btry** [comment]
The dev server was not up to date at time of testing.
