### ISSUE TITLE
Send feedback 

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/glpi-plugin#514]
**Is your feature request related to a problem? Please describe.**
We have in the dashboard a section to send feedback. But we have nowhere to send these comments.

![localhost_3000_app_about_help_feedback 1](https://user-images.githubusercontent.com/19965590/40316096-30d7e9b8-5ceb-11e8-9632-6323aa5cc05c.png)

**Describe the solution you'd like**
Create an endpoint or an item type where we can send this information.

**Additional context**
It is any type of feedback

**Comment by btry** [comment]
There is nothing in GLPI for this. I think we should change labels and localizable texts to orient this feature to issues handing.

**Comment by Gianfranco97** [comment]
At the moment we are going to create a deedlink to the mail client, to send this information

https://stackoverflow.com/questions/271171/sending-emails-with-javascript

**Comment by btry** [comment]
Sending an email when we have a ITSM tool seems weird... Which recipient email address will you use ?

**Comment by DIOHz0r** [comment]
@btry, 

This issue is more related to the dashboard than here but what if he use a Notification itemType to send the message through GLPI?.

He will send it to the email related to the dashboard support or the entity.

**Comment by Gianfranco97** [comment]
The support email of supervision

This is shown in this on the next screen:
![localhost_3000_app_about_help_4](https://user-images.githubusercontent.com/19965590/40317334-2bfd8976-5cef-11e8-80c2-4061aa4033e2.png)

**Comment by btry** [comment]
There is no notification definition to use for this lurpose , and IMO this is an bad idea to do it. Users will feedback about complains or issues, but rarely about satisfaction. Therefore, GLPI is designed to collect issues. iMO this feature is problematic because there is currently nothing in the back end for it, and I don't know how to handle it. This needs some internal discussion.

**Comment by btry** [comment]
There is no notification definition to use for this lurpose , and IMO this is an bad idea to do it. Users will feedback about complains or issues, but rarely about satisfaction. Therefore, GLPI is designed to collect issues. iMO this feature is problematic because there is currently nothing in the back end for it, and I don't know how to handle it. This needs some internal discussion.

**Comment by btry** [comment]
@Gianfranco97 OK for supervision. Expect feedbacks about this feature not running as expected by customers.

**Comment by Gianfranco97** [comment]
![r98jy-d2prw](https://user-images.githubusercontent.com/19965590/40321319-a4a6bb6a-5cfc-11e8-96e5-5d2531bbb27c.gif)
