### ISSUE TITLE
Development section on project site

### ISSUE THREAD

**Issue by Naylin15** [flyve-mdm/glpi-plugin#558]
#### Observed Results:
We must normalize the development section on the project site

  
#### Expected behavior:
coverage >>>> development/coverage/
docs >>>> development/code-documentation/
development/test-reports

**Comment by DIOHz0r** [comment]
Hi,

"development/test-reports" and "development/coverage/" are the same report because that information is generated from CI using Atoum tests, remember that there is a issue reported on Atoum's report extension project which hasn't been resolved as far as I know (https://github.com/atoum/reports-extension/issues/48).

**Comment by Naylin15** [comment]
The folder structure was added in #682

Closing
