### ISSUE TITLE
File or Applicaion directory changing

### ISSUE THREAD

**Issue by Greenstonetr** [flyve-mdm/glpi-plugin#869]
Hi,

How can I change destination directory when flyvemdm plugin upload a file or application   ?

ETC:
My server:10.0.0.1
/var/ww/html/glpi/files/_plugins/flyvemdm/file/0/5c29be57e3aa6_test.jpg

My file Server :10.0.0.2
So
is it change ?

**Comment by btry** [comment]
Hi 

Why do you need to change it ?

**Comment by Greenstonetr** [comment]
want to run servers in a redundant configuration. I have 2 servers. Therefore, I have to put both the files or applications that I have uploaded. I want to create a common directory so that the files are stored in this directory.

**Comment by btry** [comment]
HI

To match your need you should not focus on glpi/files/_plugin/flyvemdm but glpi/files, because some files may be saved by GLPI and they also need to be shared by your 2 instances. Your question is in the scope of GLPI.

You may:
- ask to the community here : https://forum.glpi-project.org/
- subscribe professional support : contact@teclib.com

**Comment by Greenstonetr** [comment]
create files
downstream.php
local_define.php
And re-install glpi
